spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html

server:
  servlet:
    context-path: /api/v1