spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/soutLink_db
    username: root
    password: root-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 1025
    username: soutLink
    password: soutLink
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: dGhlb3J5YmVsdGVuZ2luZWVycnVubmluZ2tuaWZlZnVybml0dXJlYW5vdGhlcnN0cmE=
      expiration: 86400000 # a day
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account?token={token}
  file:
    upload:
      photos-output-path: ./uploads

api:
  avatar:
    key: "a38e6be4f5914015b09fc7d5cda5ce4a"

server:
  port: 8088